server:
  port: 8000

eureka:
#   server:
#     enable-self-preservation: false
#    eviction-interval-timer-in-ms: 4000

  instance:                   #定义Eureka实例
    hostname: peer1 #Eureka实例所在的主机名

  #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
  client:
#    registerWithEureka: false #表示是否将自己注册到Eureka Server上，默认为true
#    fetchRegistry: false       #表示是否从Eureka Server上获取注册信息，默认为true
    serviceUrl:
          defaultZone: http://peer2:8001/eureka/,http://peer3:8002/eureka/

# 集群试需使用下面命令启动 打jar包后启动
#         java -jar spring-cloud-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer1
#         java -jar spring-cloud-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer2
#         java -jar spring-cloud-eureka-0.0.1-SNAPSHOT.jar --spring.profiles.active=peer3


