server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zyqjava/zyq-spring-cloud.git
          username: 544741562@qq.com
          password: ******** #这个不能说
      label: master
