server:
  port: 3000


spring:
  application:
    name: microservice-3000-customer

eureka:

  instance:                   #定义Eureka实例
    hostname: localhost #Eureka实例所在的主机名
    prefer-ip-address: true
    lease-expiration-durationn-in-seconds: 30
    lease-renewal-interval-in-seconds: 10


  #eureka默认情况下,把自己当做客户端来注册自己,所以我们要禁用它
  client:
#    registerWithEureka: false #表示是否将自己注册到Eureka Server上，默认为true
#    fetchRegistry: false       #表示是否从Eureka Server上获取注册信息，默认为true
    serviceUrl:
          defaultZone: http://peer1:8000/eureka

feign:
  hystrix:
    enabled: true


client1:
  ribbon:
    #配置首台服务器重试1次
    MaxAutoRetries: 1
    #配置其他服务器重试两次
    MaxAutoRetriesNextServer: 2
    #链接超时时间
    ConnectTimeout: 500
    #请求处理时间
    ReadTimeout: 2000
    #每个操作都开启重试机制
    OkToRetryOnAllOperations: true

#配置断路器超时时间，默认是1000（1秒）
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2001
